site_name: CARLA ScenarioRunner
repo_url: https://github.com/carla-simulator/scenario_runner
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs

nav:
- Home: 'index.md'
- Quick start:
  - 'Getting started': 'getting_started.md'
- OpenSCENARIO:
  - 'OpenSCENARIO support': 'openscenario_support.md'

markdown_extensions:
  - admonition